name: router
description: A Flutter package for handling app routing
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  authenticate:
    path: ../authenticate
  auto_route: ^10.1.0+1
  flutter:
    sdk: flutter
  profile:
    path: ../profile

dev_dependencies:
  auto_route_generator: ^10.2.3
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
