name: profile_data
description: Data Layer for User Profile (Clean Architecture)
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  get_it: ^8.0.3
  profile_domain:
    path: ../profile_domain
  shared_preferences: ^2.2.0


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
