arb-dir: lib/l10n/arb
template-arb-file: product_breakdown_en.arb
output-localization-file: product_breakdown_localizations.dart
output-class: ProductBreakdownLocalization
output-dir: lib/l10n/gen
nullable-getter: false
synthetic-package: false

# Needed to ensure the formatter does not run on the generated files.
# See https://github.com/dart-lang/dart_style/issues/864 for more information
header: "// dart format off\n// coverage:ignore-file"